### ISSUE TITLE
Convert Sign-in Flow screens from designs to static React Components

### ISSUE THREAD

**Issue by haunguyen90** [kodiakorg/dashboard-reactjs#3]
Design: https://gallery.io/projects/MCHbtQVoQ2HCZZtcns12mvPd/files/MCHbtQVoQ2HCZWmDlkklwV_I

## Todo
Sign-in flow starts from screen 1.0 to 2.2
 - [ ] Sign-in layout & background
 - [ ] Sign-in modal username/password form
 - [ ] Verification modal

## Expected
 - [ ] Use Formik for building form handling
 - [ ] Build all base form elements/components for global usage such as input, button, checkbox, dropdown,..
 - [ ] Implement form validation & error/warning
 - [ ] Screen 2.0 - focus (cursor) should go to the first input box & submit button will be disabled as default
 - [ ] Screen 2.0 - after entering every single number into the next input box, it should automatically go to the next input box
 - [ ] Screen 2.0 - After entering 4 numbers, the submit button will be submitted automatically
 - [ ] Screen 2.0 - During the submitting, the submit button should be displayed with loading indicator - see example [here](https://ant.design/components/modal/#components-modal-demo-async)
