### ISSUE TITLE
Convert Authenticated screens from designs to static React Components - s3.0 - s3.3

### ISSUE THREAD

**Issue by haunguyen90** [kodiakorg/dashboard-reactjs#4]
Design: https://gallery.io/projects/MCHbtQVoQ2HCZZtcns12mvPd/files/MCHbtQVoQ2HCZWmDlkklwV_I

Implement screens from 3.0 to 3.3

## Todo
 - [ ] Main layout & Top Search bar
 - [ ] Left side bar
    - [ ] User info
    - [ ] Statuses (with color - screen 3.1)
 - [ ] Main content
 - [ ] Float button at bottom left screen - New client button (3.3)
 - [ ] Float button at bottom right screen - Plus button (3.3)

## Expected
 - [ ] Hover effects on user info (screen 3.3)
 - [ ] Click effects for float buttons
