### ISSUE TITLE
Convert Step by Step modals from designs to static React Components

### ISSUE THREAD

**Issue by haunguyen90** [kodiakorg/dashboard-reactjs#5]
Design: https://gallery.io/projects/MCHbtQVoQ2HCZZtcns12mvPd/files/MCHbtQVoQ2HCZWmDlkklwV_I

## TODO:
 - [ ] Screen 4.0
 - [ ] Screen 4.1
 - [ ] Screen 4.2
 - [ ] Screen 4.3
 - [ ] Screen 4.4
 - [ ] Screen 4.5
 - [ ] Screen 4.6
 - [ ] Screen 4.7
 - [ ] Screen 4.8

## Expected
 - [ ] 2 buttons on the bottom left should be Cancel & Next if the current screen **IS NOT** the last step in the flow
 - [ ] 2 buttons on the bottom left should be Cancel & DONE if the current screen **IS** the last step in the flow
 - [ ] Screen 4.1 - If the selected is  `Me` ---GoTo--> 4.3 ---> 4.5 ---> 4.6 ---> 4.7
 - [ ] Screen 4.1 - If the selected is  `Couple` ---GoTo--> 4.2 ---> 4.3 ---> 4.4 ---> 4.5 ---> 4.6 ---> 4.7 ---> 4.8
 - [ ] Each button should have hover & click effects like in this [example](https://www.dropbox.com/s/tlbzlzxkupyog5x/button%20clicked%20effect.mp4?dl=0)
